version: 1.0.{build}
clone_folder: c:\projects\graptheory\
before_build:
- cmd: >-
    cd c:\projects\graptheory\lzw

    echo begin build..

    make all
build:
  parallel: true
  verbosity: normal
after_build:
- cmd: "echo zip \n7z a c:\\projects\\graptheory\\lzw\\lzw.zip * -tzip\necho done"
artifacts:
- path: lzw/release
  name: lzw.zip