version: 1.0.{build}

clone_folder: c:\projects\graptheory\

environment:

  MINGW_HOME: C:\MinGW

  MINGW_BIN: C:\MinGW\bin

  MINGW_SYS: C:\MinGW\msys\1.0

before_build:

- cmd: >-

    cd c:\projects\graptheory\lzw



    echo begin build..



    make all

build:

  parallel: true

  verbosity: normal

after_build:

- cmd: "echo zip \n7z a c:\\projects\\graptheory\\lzw\\lzw.zip * -tzip\necho done"

artifacts:

- path: lzw/release

  name: lzw.zip
