version: 1.0.{build}

clone_folder: C:\projects\graptheory\

environment:

  CYGWIN_HOME: C:\cygwin

  CYGWIN_BIN: C:\cygwin\bin

before_build:

- cmd: >-

    cd c:\projects\graptheory\lzw



    echo begin build..



    %CYGWIN_BIN%\make

build:

  parallel: true

  verbosity: normal

after_build:

- cmd: "echo zip \n7z a c:\\projects\\graptheory\\lzw\\lzw.zip * -tzip\necho done"

artifacts:

- path: lzw/release

  name: lzw.zip
