version: 1.0.{build}

clone_folder: C:\projects\graptheory\

environment:

  CYGWIN_HOME: C:\cygwin

  CYGWIN_BIN: C:\cygwin\bin

  MINGW_HOME: C:\MinGW

  MINGW_BIN: C:\MinGW\bin

  MINGW_SYS: C:\MinGW\msys\1.0

install:

- cmd: set PATH=%PATH%;C:\cygwin\bin

build_script:

- cmd: >-
    cd c:\projects\graptheory\lzw
    
    echo begin build..
    
    make

test_script:

- cmd: >-
    cd c:\projects\graptheory\lzw.exe base input encode 0
    
    cd c:\projects\graptheory\lzw.exe base encode decode 1

artifacts:

- path: lzw/lzw.exe

  name: excute file

- path: lzw/input

  name: input file
  
- path: lzw/base

  name: base character
  
- path: lzw/encode

  name: output file
  
- path: lzw/decode

  name: decode file

