version: 1.0.{build}

clone_folder: C:\projects\graptheory\

environment:

  CYGWIN_HOME: C:\cygwin

  CYGWIN_BIN: C:\cygwin\bin

  MINGW_HOME: C:\MinGW

  MINGW_BIN: C:\MinGW\bin

  MINGW_SYS: C:\MinGW\msys\1.0

install:

- cmd: set PATH=%PATH%;C:\cygwin\bin

build_script:

- cmd: >-
    cd c:\projects\graptheory\lzw



    echo begin build..



    make

test_script:

- cmd: "echo zip \n7z a c:\\projects\\graptheory\\lzw\\lzw.zip * -tzip\necho done"

artifacts:

- path: lzw

  name: lzw.zip
